### PR TITLE
fixed card style to responsive

### PR DESCRIPTION
**Pull request by ochanje210**

### CODE REVIEW

**Comment by yuda1124** [comment]
LGTM

**Comment by ovekyc** [comment]
LGTM 
Except constants.
There are a lot of constant that i cant understand.(magic numbers)
Fewer magic number has more readability

**Comment by ochanje210** [comment]
great point.

**Comment by ochanje210** [comment]
@ovekyc removed the magic numbers!

**Comment by ochanje210** [comment]
lgtm

**Pull request merged**
